### ISSUE TITLE
Issue with tmp directory

### ISSUE THREAD

**Issue by sateeshkagale** [ChuShin/dated#1]
Hi Kevin,
I am getting the following error while running dated.py:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/storage/ppl/kagales/bin/dated/dated/dated.py", line 39, in get_ds
    tmp_folder = tempfile.mkdtemp(dir="./tmp")
  File "/storage/ppl/kagales/miniconda3/envs/ks/lib/python3.6/tempfile.py", line 370, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: './tmp/tmpegtujgmo'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/storage/ppl/kagales/miniconda3/envs/ks/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/storage/ppl/kagales/miniconda3/envs/ks/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/storage/ppl/kagales/bin/dated/dated/dated.py", line 53, in get_ds
    os.chdir(cwd)
UnboundLocalError: local variable 'cwd' referenced before assignment
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/storage/ppl/kagales/bin/dated/dated/dated.py", line 103, in <module>
    main()
  File "/storage/ppl/kagales/bin/dated/dated/dated.py", line 97, in main
    calculate_ds(pairs, pep_seqdb, cds_seqdb)
  File "/storage/ppl/kagales/bin/dated/dated/dated.py", line 32, in calculate_ds
    pool.map(ds_func, pairs)
  File "/storage/ppl/kagales/miniconda3/envs/ks/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/storage/ppl/kagales/miniconda3/envs/ks/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
UnboundLocalError: local variable 'cwd' referenced before assignment

This is the command I used: dated.py *.cds.fa .*.pep.fa *.csv

**Comment by ChuShin** [comment]
Thanks. A temp output folder (prefixed "dated_") is added for storing temporary files. Fixed in 11a6a6b2e2b3394a2d382687519c861ee26ad341
